"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-07 22:53:58.717826

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buildings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('display_code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('t_hours', sa.Integer(), nullable=True),
    sa.Column('u_hours', sa.Integer(), nullable=True),
    sa.Column('l_hours', sa.Integer(), nullable=True),
    sa.Column('credits', sa.Float(), nullable=True),
    sa.Column('ects', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_courses_code'), ['code'], unique=True)

    op.create_table('faculties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('canonical_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('faculties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_faculties_canonical_name'), ['canonical_name'], unique=True)

    op.create_table('import_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=True),
    sa.Column('term_code', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instructors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('canonical_name', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('instructors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_instructors_canonical_name'), ['canonical_name'], unique=True)

    op.create_table('settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('terms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('week_count', sa.Integer(), nullable=False),
    sa.Column('periods_json', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('legacy_crbs_session_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('terms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_terms_code'), ['code'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=8), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('legacy_crbs_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('canonical_name', sa.String(length=255), nullable=False),
    sa.Column('is_evening', sa.Boolean(), nullable=False),
    sa.Column('legacy_crbs_department_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_programs_canonical_name'), ['canonical_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_programs_faculty_id'), ['faculty_id'], unique=False)

    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('floor', sa.String(length=8), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('exam_capacity', sa.Integer(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('is_bookable', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.String(length=512), nullable=True),
    sa.Column('legacy_crbs_room_id', sa.Integer(), nullable=True),
    sa.Column('room_group', sa.String(length=64), nullable=True),
    sa.Column('custom_fields', sa.JSON(), nullable=False),
    sa.Column('pos', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rooms_building_id'), ['building_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rooms_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_rooms_legacy_crbs_room_id'), ['legacy_crbs_room_id'], unique=False)

    op.create_table('schedule_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('horizon', sa.String(length=8), nullable=False),
    sa.Column('horizon_params', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('objective_value', sa.Float(), nullable=True),
    sa.Column('soft_score', sa.Integer(), nullable=True),
    sa.Column('hard_score', sa.Integer(), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.Column('diagnosis', sa.JSON(), nullable=False),
    sa.Column('parent_run_id', sa.Integer(), nullable=True),
    sa.Column('prompt_text', sa.Text(), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_run_id'], ['schedule_runs.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schedule_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedule_runs_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedule_runs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedule_runs_term_id'), ['term_id'], unique=False)

    op.create_table('weeks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('term_id', 'index', name='uq_weeks_term_index')
    )
    with op.batch_alter_table('weeks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weeks_term_id'), ['term_id'], unique=False)

    op.create_table('blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('start_period', sa.Integer(), nullable=False),
    sa.Column('end_period', sa.Integer(), nullable=False),
    sa.Column('weeks', sa.JSON(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('source_key', sa.String(length=255), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_key')
    )
    with op.batch_alter_table('blocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blocks_room_id'), ['room_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blocks_term_id'), ['term_id'], unique=False)

    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tool_calls', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['schedule_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_run_id'), ['run_id'], unique=False)

    op.create_table('constraints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=True),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('hardness', sa.String(length=8), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=8), nullable=False),
    sa.Column('nl_text', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['schedule_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('constraints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_constraints_run_id'), ['run_id'], unique=False)

    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=64), nullable=True),
    sa.Column('class_year', sa.Integer(), nullable=True),
    sa.Column('class_years', sa.JSON(), nullable=False),
    sa.Column('semester_no', sa.Integer(), nullable=True),
    sa.Column('enrolment', sa.Integer(), nullable=True),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('remote_pct', sa.Integer(), nullable=True),
    sa.Column('whole_term_in_room', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source_row', sa.JSON(), nullable=True),
    sa.Column('source_key', sa.String(length=255), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('term_id', 'source_key', name='uq_sections_term_source')
    )
    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sections_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sections_program_id'), ['program_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sections_term_id'), ['term_id'], unique=False)

    op.create_table('exam_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('course_code', sa.String(length=32), nullable=False),
    sa.Column('course_name', sa.String(length=255), nullable=True),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('faculty_text', sa.String(length=255), nullable=True),
    sa.Column('class_year', sa.Integer(), nullable=True),
    sa.Column('class_years', sa.JSON(), nullable=False),
    sa.Column('enrolment', sa.Integer(), nullable=True),
    sa.Column('instructor_text', sa.String(length=255), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('date_end', sa.Date(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('start_period', sa.Integer(), nullable=True),
    sa.Column('end_period', sa.Integer(), nullable=True),
    sa.Column('requested_venue_text', sa.Text(), nullable=True),
    sa.Column('requested_room_ids', sa.JSON(), nullable=False),
    sa.Column('requested_building', sa.String(length=16), nullable=True),
    sa.Column('requested_room_count', sa.Integer(), nullable=True),
    sa.Column('requested_min_capacity', sa.Integer(), nullable=True),
    sa.Column('requested_tags', sa.JSON(), nullable=False),
    sa.Column('invigilators_requested', sa.Integer(), nullable=True),
    sa.Column('on_campus_written', sa.Boolean(), nullable=False),
    sa.Column('no_exam', sa.Boolean(), nullable=False),
    sa.Column('needs_room', sa.Boolean(), nullable=False),
    sa.Column('definitive_room_text', sa.Text(), nullable=True),
    sa.Column('definitive_room_ids', sa.JSON(), nullable=False),
    sa.Column('merge_key', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('parse_warnings', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source_row', sa.JSON(), nullable=True),
    sa.Column('source_key', sa.String(length=255), nullable=True),
    sa.Column('source_row_index', sa.Integer(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_key')
    )
    with op.batch_alter_table('exam_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exam_requests_course_code'), ['course_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_requests_merge_key'), ['merge_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_requests_program_id'), ['program_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_requests_term_id'), ['term_id'], unique=False)

    op.create_table('meeting_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.Column('days', sa.JSON(), nullable=False),
    sa.Column('start_period', sa.Integer(), nullable=True),
    sa.Column('end_period', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('weeks', sa.JSON(), nullable=False),
    sa.Column('requested_room_text', sa.Text(), nullable=True),
    sa.Column('requested_room_ids', sa.JSON(), nullable=False),
    sa.Column('requested_building', sa.String(length=16), nullable=True),
    sa.Column('requested_tags', sa.JSON(), nullable=False),
    sa.Column('requested_capacity', sa.Integer(), nullable=True),
    sa.Column('flexible_day', sa.Boolean(), nullable=False),
    sa.Column('needs_room', sa.Boolean(), nullable=False),
    sa.Column('definitive_room_text', sa.Text(), nullable=True),
    sa.Column('definitive_room_ids', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('parse_warnings', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source_key', sa.String(length=255), nullable=True),
    sa.Column('source_row_index', sa.Integer(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_key')
    )
    with op.batch_alter_table('meeting_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meeting_requests_section_id'), ['section_id'], unique=False)

    op.create_table('section_instructors',
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('instructor_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['instructor_id'], ['instructors.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('section_id', 'instructor_id')
    )
    op.create_table('assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('meeting_request_id', sa.Integer(), nullable=True),
    sa.Column('exam_request_id', sa.Integer(), nullable=True),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('weeks', sa.JSON(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('start_period', sa.Integer(), nullable=False),
    sa.Column('end_period', sa.Integer(), nullable=False),
    sa.Column('room_ids', sa.JSON(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('course_codes', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('origin', sa.String(length=8), nullable=False),
    sa.Column('source_key', sa.String(length=255), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['exam_request_id'], ['exam_requests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['meeting_request_id'], ['meeting_requests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['schedule_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_key')
    )
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assignments_day'), ['day'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignments_exam_request_id'), ['exam_request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignments_meeting_request_id'), ['meeting_request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignments_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignments_week'), ['week'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assignments_week'))
        batch_op.drop_index(batch_op.f('ix_assignments_run_id'))
        batch_op.drop_index(batch_op.f('ix_assignments_meeting_request_id'))
        batch_op.drop_index(batch_op.f('ix_assignments_exam_request_id'))
        batch_op.drop_index(batch_op.f('ix_assignments_day'))

    op.drop_table('assignments')
    op.drop_table('section_instructors')
    with op.batch_alter_table('meeting_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meeting_requests_section_id'))

    op.drop_table('meeting_requests')
    with op.batch_alter_table('exam_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exam_requests_term_id'))
        batch_op.drop_index(batch_op.f('ix_exam_requests_program_id'))
        batch_op.drop_index(batch_op.f('ix_exam_requests_merge_key'))
        batch_op.drop_index(batch_op.f('ix_exam_requests_course_code'))

    op.drop_table('exam_requests')
    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sections_term_id'))
        batch_op.drop_index(batch_op.f('ix_sections_program_id'))
        batch_op.drop_index(batch_op.f('ix_sections_course_id'))

    op.drop_table('sections')
    with op.batch_alter_table('constraints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_constraints_run_id'))

    op.drop_table('constraints')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_run_id'))

    op.drop_table('chat_messages')
    with op.batch_alter_table('blocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blocks_term_id'))
        batch_op.drop_index(batch_op.f('ix_blocks_room_id'))

    op.drop_table('blocks')
    with op.batch_alter_table('weeks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weeks_term_id'))

    op.drop_table('weeks')
    with op.batch_alter_table('schedule_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedule_runs_term_id'))
        batch_op.drop_index(batch_op.f('ix_schedule_runs_status'))
        batch_op.drop_index(batch_op.f('ix_schedule_runs_is_active'))

    op.drop_table('schedule_runs')
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rooms_legacy_crbs_room_id'))
        batch_op.drop_index(batch_op.f('ix_rooms_code'))
        batch_op.drop_index(batch_op.f('ix_rooms_building_id'))

    op.drop_table('rooms')
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_programs_faculty_id'))
        batch_op.drop_index(batch_op.f('ix_programs_canonical_name'))

    op.drop_table('programs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('terms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_terms_code'))

    op.drop_table('terms')
    op.drop_table('settings')
    with op.batch_alter_table('instructors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instructors_canonical_name'))

    op.drop_table('instructors')
    op.drop_table('import_jobs')
    with op.batch_alter_table('faculties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_faculties_canonical_name'))

    op.drop_table('faculties')
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_courses_code'))

    op.drop_table('courses')
    op.drop_table('buildings')
    # ### end Alembic commands ###
