// Static-asset module types (*.png, *.svg, ...) from Next.js. next-env.d.ts provides the same reference
// but is generated by `next dev/build` and git-ignored, so a fresh checkout (pod CI runs `tsc` before any
// Next command) would otherwise fail with TS2307 on image imports such as src/components/ui/empty-state.tsx.
/// <reference types="next" />
/// <reference types="next/image-types/global" />
