#!/usr/bin/env python3
"""Dynamic agent memory for SmartSched (see docs/AGENTS.md).

Keeps docs/agents/registry.json (one entry per subagent: what it works on, its scope, where it left off)
and regenerates docs/AGENT_STATE.md from that registry, the ledger docs/PROGRESS.md and the static
sections in docs/agents/static.md. Claude Code hooks call it on every agent launch and finish
(.claude/settings.json), so the resume guide is always current if the session or usage limit is reached.

Usage:
    python3 scripts/agent_state.py hook-launch   # PostToolUse(Agent) payload on stdin
    python3 scripts/agent_state.py hook-stop     # SubagentStop payload on stdin
    python3 scripts/agent_state.py render        # regenerate docs/AGENT_STATE.md
    python3 scripts/agent_state.py set ID KEY=VALUE ...   # edit an entry (status, next, ledger, ...)
Hook modes never raise and always exit 0, so they cannot break a tool call.
"""

from __future__ import annotations

import fcntl
import json
import re
import subprocess
import sys
from contextlib import contextmanager
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterator

ROOT = Path(__file__).resolve().parents[1]
REGISTRY = ROOT / "docs" / "agents" / "registry.json"
STATIC = ROOT / "docs" / "agents" / "static.md"
STATE = ROOT / "docs" / "AGENT_STATE.md"
LEDGER = ROOT / "docs" / "PROGRESS.md"
LOCK = ROOT / "docs" / "agents" / ".lock"
ROW = re.compile(r"^\|\s*(?P<ts>[^|]+?)\s*\|\s*(?P<agent>[^|]+?)\s*\|\s*(?P<phase>[^|]+?)\s*\|\s*(?P<status>[^|]+?)\s*\|\s*(?P<next>[^|]*?)\s*\|\s*$")
ID_RE = re.compile(r"\b(?:agentId|agent_id|task-id|taskId)\b[\"']?\s*[:=]\s*[\"']?([A-Za-z0-9_-]{6,})")
FINISHED_SHOWN = 15


def now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M")


@contextmanager
def locked() -> Iterator[None]:
    LOCK.parent.mkdir(parents=True, exist_ok=True)
    with open(LOCK, "w") as fh:
        fcntl.flock(fh, fcntl.LOCK_EX)
        try:
            yield
        finally:
            fcntl.flock(fh, fcntl.LOCK_UN)


def load() -> dict[str, Any]:
    if REGISTRY.exists():
        try:
            data = json.loads(REGISTRY.read_text(encoding="utf-8"))
            if isinstance(data, dict) and isinstance(data.get("agents"), list):
                return data
        except json.JSONDecodeError:
            pass
    return {"agents": []}


def save(data: dict[str, Any]) -> None:
    tmp = REGISTRY.with_suffix(".tmp")
    tmp.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    tmp.replace(REGISTRY)


def find(data: dict[str, Any], agent_id: str) -> dict[str, Any] | None:
    for entry in data["agents"]:
        if entry.get("id") == agent_id:
            return entry
    return None


def section(prompt: str, name: str, limit: int = 400) -> str:
    """Text after a 'NAME:' / '## NAME' heading up to the next blank-line-separated heading."""
    m = re.search(rf"(?im)^\W*{name}\W*[:\n](.*?)(?=\n\s*\n\W*[A-Z][A-Z /&-]{{2,}}\W*[:\n]|\Z)", prompt, re.S)
    if not m:
        return ""
    text = " ".join(m.group(1).split())
    return text[:limit] + ("…" if len(text) > limit else "")


def ledger_rows() -> list[dict[str, str]]:
    if not LEDGER.exists():
        return []
    rows = []
    for line in LEDGER.read_text(encoding="utf-8").splitlines():
        m = ROW.match(line)
        if m and not m.group("ts").lower().startswith(("time", "---")):
            rows.append(m.groupdict())
    return rows


def last_ledger(entry: dict[str, Any], rows: list[dict[str, str]]) -> dict[str, str] | None:
    keys = [k.lower() for k in (entry.get("ledger"), entry.get("description")) if k]
    hit = None
    for row in rows:
        name = row["agent"].lower()
        if any(k and (k in name or name in k) for k in keys):
            hit = row
    return hit


def short(text: str, limit: int = 220) -> str:
    text = " ".join((text or "").split()).replace("|", "/")
    return text[:limit] + ("…" if len(text) > limit else "")


def git_head() -> str:
    try:
        out = subprocess.run(["git", "-C", str(ROOT), "rev-parse", "--abbrev-ref", "HEAD"], capture_output=True, text=True, timeout=5)
        sha = subprocess.run(["git", "-C", str(ROOT), "rev-parse", "--short", "HEAD"], capture_output=True, text=True, timeout=5)
        return f"`{out.stdout.strip()}` at `{sha.stdout.strip()}`"
    except Exception:  # noqa: BLE001
        return "unknown"


def render() -> None:
    data = load()
    rows = ledger_rows()
    running = [a for a in data["agents"] if a.get("status") == "running"]
    done = sorted((a for a in data["agents"] if a.get("status") != "running"), key=lambda a: a.get("finished_at") or "", reverse=True)
    out = [
        "# Agent state and resume guide",
        "",
        "<!-- GENERATED by scripts/agent_state.py from docs/agents/registry.json, docs/PROGRESS.md and",
        "     docs/agents/static.md. Do not edit by hand: edit static.md or run `agent_state.py set`. -->",
        "",
        f"Refreshed automatically on every agent launch and finish. Last refresh: **{now()} UTC**, branch {git_head()}.",
        "",
        f"## Running agents ({len(running)})",
        "",
        "| Agent id | Workstream (type) | Started | Scope fence (write) | Goal | Last ledger entry | Next |",
        "|---|---|---|---|---|---|---|",
    ]
    for a in running:
        row = last_ledger(a, rows)
        last = f"{row['ts'][11:]} {short(row['status'], 160)}" if row else "none yet"
        nxt = a.get("next") or (row["next"] if row else "")
        out.append(
            f"| `{a.get('id', '?')}` | {short(a.get('description', ''), 60)} ({a.get('subagent_type', '?')}) | {a.get('started_at', '')} "
            f"| {short(a.get('scope', ''), 200)} | {short(a.get('goal', ''), 200)} | {last} | {short(nxt, 160)} |"
        )
    if not running:
        out.append("| - | none | | | | | |")
    out += [
        "",
        f"## Recently finished agents (latest {FINISHED_SHOWN} of {len(done)}; full list in docs/agents/registry.json)",
        "",
        "| Agent id | Workstream | Status | Finished | Where it left off |",
        "|---|---|---|---|---|",
    ]
    for a in done[:FINISHED_SHOWN]:
        row = last_ledger(a, rows)
        left = a.get("left_off") or (short(row["status"], 200) if row else "")
        out.append(f"| `{a.get('id', '?')}` | {short(a.get('description', ''), 60)} | {a.get('status')} | {a.get('finished_at', '')} | {short(left, 220)} |")
    out.append("")
    if STATIC.exists():
        out.append(STATIC.read_text(encoding="utf-8").rstrip())
        out.append("")
    STATE.write_text("\n".join(out), encoding="utf-8")


def read_payload() -> dict[str, Any]:
    raw = sys.stdin.read() if not sys.stdin.isatty() else ""
    try:
        payload = json.loads(raw) if raw.strip() else {}
    except json.JSONDecodeError:
        payload = {}
    payload["_raw"] = raw
    return payload


def agent_id_from(payload: dict[str, Any]) -> str | None:
    for key in ("agent_id", "agentId"):
        if isinstance(payload.get(key), str):
            return payload[key]
    resp = payload.get("tool_response")
    if isinstance(resp, dict):
        for key in ("agentId", "agent_id", "taskId", "task_id", "id"):
            if isinstance(resp.get(key), str):
                return resp[key]
    m = ID_RE.search(json.dumps(resp) if resp is not None else payload["_raw"])
    return m.group(1) if m else None


def hook_launch() -> None:
    payload = read_payload()
    if payload.get("tool_name") not in (None, "Agent", "Task"):
        return
    ti = payload.get("tool_input") or {}
    prompt = str(ti.get("prompt", ""))
    agent_id = agent_id_from(payload) or f"unknown-{now().replace(' ', 'T')}"
    resp_text = json.dumps(payload.get("tool_response", ""))[:4000].lower()
    background = ti.get("run_in_background", True) is not False and "completed" not in resp_text[:200]
    with locked():
        data = load()
        entry = find(data, agent_id) or {"id": agent_id}
        if entry not in data["agents"]:
            data["agents"].append(entry)
        entry.update(
            description=ti.get("description", entry.get("description", "")),
            subagent_type=ti.get("subagent_type", entry.get("subagent_type", "general-purpose")),
            isolation=ti.get("isolation"),
            started_at=entry.get("started_at") or now(),
            scope=section(prompt, "SCOPE") or section(prompt, "WRITE SCOPE") or entry.get("scope", ""),
            goal=section(prompt, "GOAL") or section(prompt, "TASK") or short(prompt, 300),
            ledger=section(prompt, "LEDGER NAME", 80) or entry.get("ledger") or ti.get("description", ""),
            resumed="RESUMING" in prompt[:400],
        )
        if background:
            entry["status"] = "running"
        else:  # foreground agents have already finished when PostToolUse fires
            entry.update(status="finished", finished_at=now(), left_off=short(resp_text, 300))
        save(data)
        render()


def hook_stop() -> None:
    payload = read_payload()
    agent_id = agent_id_from(payload)
    if not agent_id:
        return
    with locked():
        data = load()
        entry = find(data, agent_id)
        if entry is None:
            entry = {"id": agent_id, "description": payload.get("agent_type", ""), "subagent_type": payload.get("agent_type", "?")}
            data["agents"].append(entry)
        entry.update(status="finished", finished_at=now())
        msg = payload.get("last_assistant_message") or payload.get("result")
        if isinstance(msg, str) and msg.strip():
            entry["left_off"] = short(msg, 400)
        save(data)
        render()


def cmd_set(args: list[str]) -> None:
    agent_id, pairs = args[0], args[1:]
    with locked():
        data = load()
        entry = find(data, agent_id)
        if entry is None:
            entry = {"id": agent_id, "started_at": now()}
            data["agents"].append(entry)
        for pair in pairs:
            key, _, value = pair.partition("=")
            entry[key] = value
        if entry.get("status") in ("finished", "failed", "stopped") and not entry.get("finished_at"):
            entry["finished_at"] = now()
        save(data)
        render()


def main(argv: list[str]) -> int:
    mode = argv[1] if len(argv) > 1 else "render"
    if mode in ("hook-launch", "hook-stop"):
        try:
            hook_launch() if mode == "hook-launch" else hook_stop()
        except Exception as exc:  # noqa: BLE001 - a hook must never break the tool call
            print(f"agent_state: {exc}", file=sys.stderr)
        return 0
    if mode == "set" and len(argv) >= 3:
        cmd_set(argv[2:])
        return 0
    if mode == "render":
        with locked():
            render()
        return 0
    print(__doc__)
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv))
