"""ORM models. Import this package to register all tables on ``Base.metadata``."""

from app.models.approvals import (
    ApprovalDecision,
    ApprovalRequest,
    ApprovalRule,
    ApproverScope,
    InAppNotification,
)
from app.models.audit import AuditEvent
from app.models.base import Base
from app.models.booking import (
    Booking,
    BookingPeriod,
    BookingSchedule,
    BookingSeries,
    BookingSlot,
    Holiday,
    MultiBooking,
    MultiBookingSlot,
    NotificationOutbox,
    PasswordResetToken,
    Permission,
    Role,
    RolePermission,
    RoomAcl,
    RoomAclPermission,
    RoomCustomField,
    RoomCustomFieldOption,
    RoomCustomFieldValue,
    RoomGroup,
    TermBookingSettings,
    TermDate,
    TermSchedule,
    TimetableWeek,
    Translation,
    UserConstraint,
)
from app.models.catalog import Building, Course, Faculty, Instructor, Program, Room, Term, Week
from app.models.integrations import (
    CalendarConnection,
    CalendarEventLink,
    CalendarEventRevision,
    CalendarFeedToken,
    CalendarSyncJob,
    OAuthState,
    WebhookDelivery,
    WebhookEndpoint,
)
from app.models.runs import Assignment, ChatApplyClaim, ChatMessage, ScheduleRun
from app.models.scheduling import (
    Block,
    ConstraintRow,
    ExamRequest,
    MeetingRequest,
    Section,
    SectionInstructor,
)
from app.models.studio import ImportedSnapshot, StudioDraft, StudioPreset
from app.models.system import ImportJob, Setting, User

__all__ = [
    "CalendarConnection",
    "CalendarEventLink",
    "CalendarEventRevision",
    "CalendarFeedToken",
    "CalendarSyncJob",
    "OAuthState",
    "WebhookDelivery",
    "WebhookEndpoint",
    "ApprovalDecision",
    "ApprovalRequest",
    "ApprovalRule",
    "ApproverScope",
    "Assignment",
    "AuditEvent",
    "Base",
    "Block",
    "Booking",
    "BookingPeriod",
    "BookingSchedule",
    "BookingSeries",
    "BookingSlot",
    "Building",
    "ChatApplyClaim",
    "ChatMessage",
    "ConstraintRow",
    "Course",
    "ExamRequest",
    "Faculty",
    "Holiday",
    "ImportJob",
    "ImportedSnapshot",
    "InAppNotification",
    "Instructor",
    "MeetingRequest",
    "MultiBooking",
    "MultiBookingSlot",
    "NotificationOutbox",
    "PasswordResetToken",
    "Permission",
    "Program",
    "Role",
    "RolePermission",
    "Room",
    "RoomAcl",
    "RoomAclPermission",
    "RoomCustomField",
    "RoomCustomFieldOption",
    "RoomCustomFieldValue",
    "RoomGroup",
    "ScheduleRun",
    "Section",
    "SectionInstructor",
    "Setting",
    "StudioDraft",
    "StudioPreset",
    "Term",
    "TermBookingSettings",
    "TermDate",
    "TermSchedule",
    "TimetableWeek",
    "Translation",
    "User",
    "UserConstraint",
    "Week",
]
